### ISSUE TITLE
Manifest v3 chrome.action is undefined

### ISSUE THREAD

**Issue by RolandWarburton** [inflatablegrade/Extension-with-WASM#3]
Hi all,

I get the following issue when running the repository as is.

```none
index.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'onClicked')
```

I think this is caused by `chrome.action` being undefined in main.js

Any advice how to overcome this error? perhaps WASM and mv3 are broken at the moment.

**Comment by inflatablegrade** [comment]
I couldn't repro it for some time, but now I'm getting some results.

The v2 version works properly on my Opera, Firefox and Edge, but not on Chrome. It throws this error there:

```
content_script.js:18 Uncaught (in promise) CompileError: WebAssembly.instantiate(): 
    at content_script.js:18:15
```

The v3 version works properly on my Opera and Edge. On FF, it gives this:

`background.service_worker is currently disabled`

On Chrome, it doesn't work at all.

**Comment by inflatablegrade** [comment]
Updated. Now I got to work it on Chrome (as far as websites allow it anyway).

The stuff with Firefox is it [not supporting service workers](https://github.com/mozilla/web-ext/issues/2532#issuecomment-1285039773).

**Comment by RolandWarburton** [comment]
> Updated. Now I got to work it on Chrome (as far as websites allow it anyway).
> 
> The stuff with Firefox is it [not supporting service workers](https://github.com/mozilla/web-ext/issues/2532#issuecomment-1285039773).

By getting it working on chrome do you mean using `wasm-unsafe-eval`? [mdm](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_webassembly_execution).

i should have mentioned my main interests are in making it work on chrome.

**Comment by inflatablegrade** [comment]
Not really. I modified [manifest.json](https://github.com/inflatablegrade/Extension-with-WASM/blob/manifest-v3/manifest.json) and [content_script.js](https://github.com/inflatablegrade/Extension-with-WASM/blob/manifest-v3/content_script.js). The former to change the background into a service worker, the latter to turn instantiate into instantiateStreaming.

**Comment by RolandWarburton** [comment]
Ah i see, sorry. Thank you i confirm its working for me too :)
